[package]
name = "spacely2"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "mainnet", addr_subst = { "std" = "0x1" } }

[addresses]
spacely2 = "720757d34c77743730715fcf091f456e6840e32a077014d6883983ff7323c3ea"
