[package]
name = "spacely3"
version = "1.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "mainnet" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "mainnet", addr_subst = { "std" = "0x1" } }

[addresses]
std = "0x1"
aptos_framework = "0x1"
aptos_std = "0x1"
spacely3 = "0x7a0bc01a9e12a99db2350fe7b96595cf1577adb3e05a5afcf4d3d5faacb7f228"
